76 add react i18next library and refactor texts
ErlingHauan/FormFactory pull request #82
Opened 2024-02-23 08:10 UTC by JamalAlabdullah

Added react i18next library to save all texts in an own json file.

2024-02-23 08:16 UTC, JamalAlabdullah commented
We have error in test because we need to mock the translation for all tests. I will add an issue for this

2024-02-26 07:52 UTC, ErlingHauan commented on frontend/language/src/nor.json
Filename is "nor.json", but text is in English.

2024-02-26 07:53 UTC, ErlingHauan commented on frontend/language/src/nor.json
> +"settings_side_bar.minimum.lenght": "Minimum length",
Typo in key

2024-02-26 07:53 UTC, ErlingHauan commented on frontend/language/src/nor.json
> +"settings_side_bar.maximum.lenght": "Maximum length",
Typo in key

2024-02-26 07:56 UTC, ErlingHauan commented on frontend/main-app/src/app/App.tsx
Language metadata should be changed to English 😊

2024-02-26 07:58 UTC, ErlingHauan commented on frontend/main-app/src/app/App.test.tsx
> +    const title = screen.getByRole("link", { name: "Form Builder" });
Possible to use "name: header_form.factory.title.link"?

2024-02-26 08:05 UTC, ErlingHauan commented on frontend/main-app/src/components/Login/Login.test.tsx
> +  it("loads and displays Login component", async () => {
I don't think async is required when using getByRole and getByLabelText
https://testing-library.com/docs/dom-testing-library/api-async/

2024-02-26 08:12 UTC, ErlingHauan commented on frontend/main-app/src/components/Login/Login.tsx
> +          label="signup_page.email.label"
```suggestion
          label={t("signup_page.password.label")}
```

2024-02-26 08:15 UTC, ErlingHauan requested changes
Nice work! 😊
I found some small things you can take a look at

2024-02-26 08:15 UTC, ErlingHauan commented on frontend/main-app/src/components/Login/Login.tsx
> +          label="signup_page.password.label"
```suggestion
          label={t("signup_page.password.label")}
```

2024-02-26 12:42 UTC, JamalAlabdullah commented on frontend/language/src/nor.json
Right,  we use english 👍😊

2024-02-27 07:08 UTC, ErlingHauan approved these changes
Good work! Very useful to have the texts sentralized in a JSON file 💯

2024-02-27 07:43 UTC, merged