Add dashboard page
ErlingHauan/FormFactory pull request #91
Opened 2024-02-27 09:51 UTC by ErlingHauan

This PR adds a dashboard page to the app. The dashboard uses Designsystemet's accordion and modal components to display information about a user's created forms.

When login or signup is successful, the app now redirects to the dashboard.

Closes #39 

https://github.com/ErlingHauan/FormFactory/assets/148075168/7bb6f415-b194-475b-9a08-4f51240d9f30

2024-02-27 13:18 UTC, lassopicasso requested changes
Well done with this :) I have some comments below.

2024-02-27 13:18 UTC, lassopicasso commented on frontend/main-app/src/components/Dashboard/Dashboard.tsx
> +  );
I recommend structuring the dashboard in a way that aligns with how we handle actual data. I've also refactored certain parts to enhance reusability. 
This is just a suggestion for better alignment with our future data needs. Feel free to structure it differently, but I believe taking the future data into consideration would be beneficial. 😃

2024-02-27 13:18 UTC, lassopicasso commented on frontend/main-app/src/components/FormModal/FormModal.tsx
> +    </Modal.Root>
Perhaps we could also consider how this aligns with actual data, potentially enhancing the reusability of elements, similar to my suggestion for the dashboard. :)

2024-02-28 12:02 UTC, lassopicasso approved these changes
Well done! 👏 🚀

2024-02-28 12:03 UTC, ErlingHauan commented
PR updated! Changes:
* Dashboard now lists all forms that are displayed in a "formData.json" file.
* FormModal now lists all submissions from a  "submittedData.json" file.
* Created a reusable CustomParagraph component.

2024-02-28 12:07 UTC, merged